[package]
name = "shoco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordermap = "*"

# [[bin]]
# name = "gen_model"
# path = "src/gen_model_test.rs"
# 
# [profile.release]
# debug = true
